name: QA - Lint C++ Sources
on:
  push:
    branches:
    - main
  pull_request:

env:
  pull_request_id: ${{ github.event.pull_request.number }}
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  quality:
    name: Lint C++ sources with LLVM
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.0.2
      # Ensures compilation of message resources before clang-tidy. Fails fast if that's not possible.
      - name: Generates Launcher compilation artifacts
        shell: powershell
        run: |
          msbuild -p:Platform=x64 -p:Configuration=Debug .\DistroLauncher\DistroLauncher.vcxproj
      # Produces the fixes.yaml to be consumed by the commenter.
      - name: Run Clang-Tidy.
        shell: powershell
        run: | 
          copy .github\workflows\clang_lint\msbuild\Directory.Build.props DistroLauncher\
          msbuild -p:Platform=x64 -p:Configuration=Debug -t:ClangTidy DistroLauncher\DistroLauncher.vcxproj
      # Runs clang-format. At this point clang-tidy already ran and produced the fixes.yaml.
      # This piece is meant to be cross-platform to enable maximum future reuse. That's why bash.
      - name: Lint with Clang tools
        shell: bash
        run: |
          chmod +x .github/workflows/clang_lint/entrypoint.sh
          .github/workflows/clang_lint/entrypoint.sh
